version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: eshop-keycloak:v1.0.0
      build:
        context: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_IMPORT: /tmp/eshop-realm.json
      ports:
        - 8080:8080
      depends_on:
        - postgres
  frontend:
      image: eshop-frontend:v1.0.0
      build:
        context: e-shop-frontend
      ports:
        - 3000:80
  app:
      image: eshop-app:v1.0.0
      build:
        context: e-shop-backend
      ports:
        - 9090:9090
      depends_on:
        - keycloak
  rabbitmq:
      image: rabbitmq:3.8.7-management-alpine
      ports:
        - 15672:15672
